//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroTickets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetroInstructionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetroInstructionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetroTickets.MetroInstructionStrings", typeof(MetroInstructionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cash Value.
        /// </summary>
        internal static string AddCashValue {
            get {
                return ResourceManager.GetString("AddCashValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy an EASY Card or EASY Ticket.
        /// </summary>
        internal static string BuyCardOrTicket {
            get {
                return ResourceManager.GetString("BuyCardOrTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy EASY Card.
        /// </summary>
        internal static string BuyEasyCard {
            get {
                return ResourceManager.GetString("BuyEasyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card is valid for three years
        ///-Load it with 1-Day Pass, 7-Day Pass, or a 1-Month Pass and/or cash value of up to $150
        ///-Buy an EASY card if you are loading a 1-Month Pass or a 1-Month Pass with a monthly Metrorail Parking permit..
        /// </summary>
        internal static string BuyEasyCardDetails {
            get {
                return ResourceManager.GetString("BuyEasyCardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy EASY Ticket.
        /// </summary>
        internal static string BuyEasyTicket {
            get {
                return ResourceManager.GetString("BuyEasyTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Ideal for short-term use. 
        ///-The ticket expires 60 days from date of purchase.
        ///-Load it with a 1-Day Pass, 7-Day Pass or cash value of up to $40.
        /// </summary>
        internal static string BuyEasyTicketDetails {
            get {
                return ResourceManager.GetString("BuyEasyTicketDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Schedule.
        /// </summary>
        internal static string CheckSchedule {
            get {
                return ResourceManager.GetString("CheckSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current balance is $10..
        /// </summary>
        internal static string CurrentBalance10USD {
            get {
                return ResourceManager.GetString("CurrentBalance10USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Passes.
        /// </summary>
        internal static string DayPasses {
            get {
                return ResourceManager.GetString("DayPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the metro kiosk below to complete the prompted tasks.
        /// </summary>
        internal static string IntroMessage {
            get {
                return ResourceManager.GetString("IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an EASY Card or EASY Ticket.
        /// </summary>
        internal static string LoadCardOrTicket {
            get {
                return ResourceManager.GetString("LoadCardOrTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a selection from the options below:.
        /// </summary>
        internal static string MakeSelectionBelow {
            get {
                return ResourceManager.GetString("MakeSelectionBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-Day Ticket: Cost $5.00.
        /// </summary>
        internal static string OneDayTicket {
            get {
                return ResourceManager.GetString("OneDayTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Unlimited Rides for one calender day
        ///-Valid from the time you first tap your card or ticket on a Metrorail faregate or Metrobus farebox until 2 a.m. the following day..
        /// </summary>
        internal static string OneDayTicketDetails {
            get {
                return ResourceManager.GetString("OneDayTicketDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-Month Pass.
        /// </summary>
        internal static string OneMonthPass {
            get {
                return ResourceManager.GetString("OneMonthPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available from the 20th day of the proceeding month to the 10th day of the month for which you are purchasing the pass.
        /// </summary>
        internal static string OneMonthPassDetails {
            get {
                return ResourceManager.GetString("OneMonthPassDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-Month Pass + Parking.
        /// </summary>
        internal static string OneMonthPassPlusParking {
            get {
                return ResourceManager.GetString("OneMonthPassPlusParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available from the 20th day of the proceeding month to the 10th day of the month for which you are purchasing the pass or permit.
        /// </summary>
        internal static string OneMonthPassPlusParkingDetails {
            get {
                return ResourceManager.GetString("OneMonthPassPlusParkingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! Please proceed to the next task.
        /// </summary>
        internal static string ProceedNextTaskPrompt {
            get {
                return ResourceManager.GetString("ProceedNextTaskPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to main screen.
        /// </summary>
        internal static string ReturnToMainScreen {
            get {
                return ResourceManager.GetString("ReturnToMainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-Day Ticket: Cost $26.00.
        /// </summary>
        internal static string SevenDayTicket {
            get {
                return ResourceManager.GetString("SevenDayTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Unlimited Rides for seven consecutive calender days 
        ///-Valid from the time you first tap your card or ticket on a Metrorail faregate or Metrobus farebox..
        /// </summary>
        internal static string SevenDayTicketDetails {
            get {
                return ResourceManager.GetString("SevenDayTicketDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in Miami for a week and you expect to use public transportation extensively during that time. Using the transportation pass dispenser, purchase the pass that you will need during your stay here, keeping in mind that you will be returning to Miami in 3 months and you want to use the same pass then..
        /// </summary>
        internal static string SubTask1_Instructions {
            get {
                return ResourceManager.GetString("SubTask1_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are waiting for a friend to meet up with you at the metrorail station. You have a metro pass, but your friend does not. Since you will both be using the metro transportation system most of the day, purchase a pass for your friend while you wait for him..
        /// </summary>
        internal static string SubTask2_Instructions {
            get {
                return ResourceManager.GetString("SubTask2_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not sure how much money you have on your easy card, but you want to make sure that you have $30 on it to last you through the rest of the month. Please use the system to make sure of it..
        /// </summary>
        internal static string SubTask3_Instructions {
            get {
                return ResourceManager.GetString("SubTask3_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like more time to complete this task?.
        /// </summary>
        internal static string SubtaskMoreTimePrompt {
            get {
                return ResourceManager.GetString("SubtaskMoreTimePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To begin, tap your card on the reader below:.
        /// </summary>
        internal static string TapCardOnReader {
            get {
                return ResourceManager.GetString("TapCardOnReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for completing this task.
        /// </summary>
        internal static string ThankYouForCompletingTask {
            get {
                return ResourceManager.GetString("ThankYouForCompletingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To begin, please make a selection from the options below:.
        /// </summary>
        internal static string ToBeginMakeSelection {
            get {
                return ResourceManager.GetString("ToBeginMakeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your task is.
        /// </summary>
        internal static string YourTaskIs {
            get {
                return ResourceManager.GetString("YourTaskIs", resourceCulture);
            }
        }
    }
}
