//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication1.Images", typeof(Images).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Medication_D-Anaanx.JPG.
        /// </summary>
        internal static string Anaanx {
            get {
                return ResourceManager.GetString("Anaanx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Medication_B-BRB.JPG.
        /// </summary>
        internal static string BRB {
            get {
                return ResourceManager.GetString("BRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Medication_E-Cyclomeovan.JPG.
        /// </summary>
        internal static string Cyclomeovan {
            get {
                return ResourceManager.GetString("Cyclomeovan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Dri-Tab.jpg.
        /// </summary>
        internal static string DriTab {
            get {
                return ResourceManager.GetString("DriTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Medication_C-Linophen.JPG.
        /// </summary>
        internal static string Linophen {
            get {
                return ResourceManager.GetString("Linophen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Medication_A-Parlenol.JPG.
        /// </summary>
        internal static string Parlenol {
            get {
                return ResourceManager.GetString("Parlenol", resourceCulture);
            }
        }
    }
}
