//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuestionStrings_es
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuestionStrings_es()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication1.QuestionStrings_es", typeof(QuestionStrings_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Call the lab to cancel your blood work appointment..
        /// </summary>
        internal static string CallTheLab
        {
            get
            {
                return ResourceManager.GetString("CallTheLab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Call my office at least 24-hours in advance of your appointment time..
        /// </summary>
        internal static string CMO24HrsAdvance
        {
            get
            {
                return ResourceManager.GetString("CMO24HrsAdvance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Call my office the morning of your appointment..
        /// </summary>
        internal static string CMOMorning
        {
            get
            {
                return ResourceManager.GetString("CMOMorning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do not eat anything after midnight the day before your visit. You can drink milk, juice or coffee..
        /// </summary>
        internal static string DNEAAMidnight
        {
            get
            {
                return ResourceManager.GetString("DNEAAMidnight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do not eat anything after you wake up on the day of your visit. You can drink milk, juice or coffee..
        /// </summary>
        internal static string DNEAAWakeup
        {
            get
            {
                return ResourceManager.GetString("DNEAAWakeup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drink only water after midnight the day before your visit. You cannot eat food or drink anything other than water..
        /// </summary>
        internal static string DrinkOnlyWater
        {
            get
            {
                return ResourceManager.GetString("DrinkOnlyWater", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Continue to take the same dose of the Dri-Tab medication..
        /// </summary>
        internal static string DriTabContinue
        {
            get
            {
                return ResourceManager.GetString("DriTabContinue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Double the dose of the Dri-Tab medication..
        /// </summary>
        internal static string DriTabDoubleDose
        {
            get
            {
                return ResourceManager.GetString("DriTabDoubleDose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop the medication and contact my doctor..
        /// </summary>
        internal static string DriTabStop
        {
            get
            {
                return ResourceManager.GetString("DriTabStop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Take the Dri-Tab medication with milk..
        /// </summary>
        internal static string DriTabTakeWithMilk
        {
            get
            {
                return ResourceManager.GetString("DriTabTakeWithMilk", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 15 days.
        /// </summary>
        internal static string FifteenDays
        {
            get
            {
                return ResourceManager.GetString("FifteenDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 5 days.
        /// </summary>
        internal static string FiveDays
        {
            get
            {
                return ResourceManager.GetString("FiveDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Have a full breakfast before you arrive for your visit, as you will not be able to eat or drink anything all morning while you are undergoing the tests..
        /// </summary>
        internal static string HaveAFullBreakfast
        {
            get
            {
                return ResourceManager.GetString("HaveAFullBreakfast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know..
        /// </summary>
        internal static string IDK
        {
            get
            {
                return ResourceManager.GetString("IDK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A list of your medications.
        /// </summary>
        internal static string ListOfMeds
        {
            get
            {
                return ResourceManager.GetString("ListOfMeds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No
        {
            get
            {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None of the above.
        /// </summary>
        internal static string NoneOfTheAbove
        {
            get
            {
                return ResourceManager.GetString("NoneOfTheAbove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One week from today in the afternoon.
        /// </summary>
        internal static string OWFTAfternoon
        {
            get
            {
                return ResourceManager.GetString("OWFTAfternoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One week from today in the morning.
        /// </summary>
        internal static string OWFTMorning
        {
            get
            {
                return ResourceManager.GetString("OWFTMorning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 10 days.
        /// </summary>
        internal static string TenDays
        {
            get
            {
                return ResourceManager.GetString("TenDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 20 days.
        /// </summary>
        internal static string TwentyDays
        {
            get
            {
                return ResourceManager.GetString("TwentyDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 25 days.
        /// </summary>
        internal static string TwentyfiveDays
        {
            get
            {
                return ResourceManager.GetString("TwentyfiveDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Two weeks from today in the afternoon.
        /// </summary>
        internal static string TWFTAfternoon
        {
            get
            {
                return ResourceManager.GetString("TWFTAfternoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Two weeks from today in the morning.
        /// </summary>
        internal static string TWFTMorning
        {
            get
            {
                return ResourceManager.GetString("TWFTMorning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes
        {
            get
            {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your driver&apos;s license.
        /// </summary>
        internal static string YourDriversLicense
        {
            get
            {
                return ResourceManager.GetString("YourDriversLicense", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your insurance card.
        /// </summary>
        internal static string YourInsuranceCard
        {
            get
            {
                return ResourceManager.GetString("YourInsuranceCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your social security card.
        /// </summary>
        internal static string YourSSCard
        {
            get
            {
                return ResourceManager.GetString("YourSSCard", resourceCulture);
            }
        }
    }
}
