//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Videos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Videos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication1.Videos", typeof(Videos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-VIDEO-EN01a.wmv.
        /// </summary>
        internal static string INFO_1A {
            get {
                return ResourceManager.GetString("INFO_1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-VIDEO-EN01b.wmv.
        /// </summary>
        internal static string INFO_1B {
            get {
                return ResourceManager.GetString("INFO_1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-VIDEO-EN01c.wmv.
        /// </summary>
        internal static string INFO_1C {
            get {
                return ResourceManager.GetString("INFO_1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-VIDEO-EN02a.wmv.
        /// </summary>
        internal static string INFO_2A {
            get {
                return ResourceManager.GetString("INFO_2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-VIDEO-EN02b.wmv.
        /// </summary>
        internal static string INFO_2B {
            get {
                return ResourceManager.GetString("INFO_2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-VIDEO-EN02c.wmv.
        /// </summary>
        internal static string INFO_2C {
            get {
                return ResourceManager.GetString("INFO_2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-INTRO.wmv.
        /// </summary>
        internal static string INTRO {
            get {
                return ResourceManager.GetString("INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-MSG01.wmv.
        /// </summary>
        internal static string MSG01 {
            get {
                return ResourceManager.GetString("MSG01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-MSG02.wmv.
        /// </summary>
        internal static string MSG02 {
            get {
                return ResourceManager.GetString("MSG02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-Q01.wmv.
        /// </summary>
        internal static string Q01_01 {
            get {
                return ResourceManager.GetString("Q01_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN02-Q01.wmv.
        /// </summary>
        internal static string Q01_02 {
            get {
                return ResourceManager.GetString("Q01_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-Q02.wmv.
        /// </summary>
        internal static string Q02_01 {
            get {
                return ResourceManager.GetString("Q02_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN02-Q02.wmv.
        /// </summary>
        internal static string Q02_02 {
            get {
                return ResourceManager.GetString("Q02_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-Q03.wmv.
        /// </summary>
        internal static string Q03_01 {
            get {
                return ResourceManager.GetString("Q03_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN03-Q03.wmv.
        /// </summary>
        internal static string Q03_03 {
            get {
                return ResourceManager.GetString("Q03_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-Q04.wmv.
        /// </summary>
        internal static string Q04_01 {
            get {
                return ResourceManager.GetString("Q04_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN04-Q04.wmv.
        /// </summary>
        internal static string Q04_04 {
            get {
                return ResourceManager.GetString("Q04_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-Q05.wmv.
        /// </summary>
        internal static string Q05_01 {
            get {
                return ResourceManager.GetString("Q05_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-Q06.wmv.
        /// </summary>
        internal static string Q06_01 {
            get {
                return ResourceManager.GetString("Q06_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-Q07.wmv.
        /// </summary>
        internal static string Q07_01 {
            get {
                return ResourceManager.GetString("Q07_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-Q08.wmv.
        /// </summary>
        internal static string Q08_01 {
            get {
                return ResourceManager.GetString("Q08_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-Q09.wmv.
        /// </summary>
        internal static string Q09_01 {
            get {
                return ResourceManager.GetString("Q09_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-Q10.wmv.
        /// </summary>
        internal static string Q10_01 {
            get {
                return ResourceManager.GetString("Q10_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-Q11.wmv.
        /// </summary>
        internal static string Q11_01 {
            get {
                return ResourceManager.GetString("Q11_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-Q12.wmv.
        /// </summary>
        internal static string Q12_01 {
            get {
                return ResourceManager.GetString("Q12_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Videos_EN\DRT-EN01-Q13.wmv.
        /// </summary>
        internal static string Q13_01 {
            get {
                return ResourceManager.GetString("Q13_01", resourceCulture);
            }
        }
    }
}
