//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TasksMainMenu
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class tasksDataContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new tasksDataContainer object using the connection string found in the 'tasksDataContainer' section of the application configuration file.
        /// </summary>
        public tasksDataContainer() : base("name=tasksDataContainer", "tasksDataContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new tasksDataContainer object.
        /// </summary>
        public tasksDataContainer(string connectionString) : base(connectionString, "tasksDataContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new tasksDataContainer object.
        /// </summary>
        public tasksDataContainer(EntityConnection connection) : base(connection, "tasksDataContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<newParticipant> newParticipants
        {
            get
            {
                if ((_newParticipants == null))
                {
                    _newParticipants = base.CreateObjectSet<newParticipant>("newParticipants");
                }
                return _newParticipants;
            }
        }
        private ObjectSet<newParticipant> _newParticipants;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TaskData> TaskDatas
        {
            get
            {
                if ((_TaskDatas == null))
                {
                    _TaskDatas = base.CreateObjectSet<TaskData>("TaskDatas");
                }
                return _TaskDatas;
            }
        }
        private ObjectSet<TaskData> _TaskDatas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the newParticipants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonewParticipants(newParticipant newParticipant)
        {
            base.AddObject("newParticipants", newParticipant);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TaskDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTaskDatas(TaskData taskData)
        {
            base.AddObject("TaskDatas", taskData);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tasksData", Name="newParticipant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class newParticipant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new newParticipant object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="participantID">Initial value of the ParticipantID property.</param>
        /// <param name="age">Initial value of the Age property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="timepoint">Initial value of the Timepoint property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        public static newParticipant CreatenewParticipant(global::System.Int32 id, global::System.String participantID, global::System.Int32 age, global::System.String gender, global::System.Int32 timepoint, global::System.DateTime timestamp)
        {
            newParticipant newParticipant = new newParticipant();
            newParticipant.Id = id;
            newParticipant.ParticipantID = participantID;
            newParticipant.Age = age;
            newParticipant.Gender = gender;
            newParticipant.Timepoint = timepoint;
            newParticipant.Timestamp = timestamp;
            return newParticipant;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ParticipantID
        {
            get
            {
                return _ParticipantID;
            }
            set
            {
                OnParticipantIDChanging(value);
                ReportPropertyChanging("ParticipantID");
                _ParticipantID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ParticipantID");
                OnParticipantIDChanged();
            }
        }
        private global::System.String _ParticipantID;
        partial void OnParticipantIDChanging(global::System.String value);
        partial void OnParticipantIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.Int32 _Age;
        partial void OnAgeChanging(global::System.Int32 value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Timepoint
        {
            get
            {
                return _Timepoint;
            }
            set
            {
                OnTimepointChanging(value);
                ReportPropertyChanging("Timepoint");
                _Timepoint = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Timepoint");
                OnTimepointChanged();
            }
        }
        private global::System.Int32 _Timepoint;
        partial void OnTimepointChanging(global::System.Int32 value);
        partial void OnTimepointChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tasksData", Name="TaskData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TaskData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TaskData object.
        /// </summary>
        /// <param name="taskDataId">Initial value of the TaskDataId property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="eventType">Initial value of the EventType property.</param>
        /// <param name="eventData">Initial value of the EventData property.</param>
        /// <param name="taskName">Initial value of the TaskName property.</param>
        /// <param name="subjectID">Initial value of the SubjectID property.</param>
        public static TaskData CreateTaskData(global::System.Int32 taskDataId, global::System.DateTime time, global::System.String eventType, global::System.String eventData, global::System.String taskName, global::System.String subjectID)
        {
            TaskData taskData = new TaskData();
            taskData.TaskDataId = taskDataId;
            taskData.Time = time;
            taskData.EventType = eventType;
            taskData.EventData = eventData;
            taskData.TaskName = taskName;
            taskData.SubjectID = subjectID;
            return taskData;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TaskDataId
        {
            get
            {
                return _TaskDataId;
            }
            set
            {
                if (_TaskDataId != value)
                {
                    OnTaskDataIdChanging(value);
                    ReportPropertyChanging("TaskDataId");
                    _TaskDataId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TaskDataId");
                    OnTaskDataIdChanged();
                }
            }
        }
        private global::System.Int32 _TaskDataId;
        partial void OnTaskDataIdChanging(global::System.Int32 value);
        partial void OnTaskDataIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.DateTime _Time;
        partial void OnTimeChanging(global::System.DateTime value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EventType
        {
            get
            {
                return _EventType;
            }
            set
            {
                OnEventTypeChanging(value);
                ReportPropertyChanging("EventType");
                _EventType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EventType");
                OnEventTypeChanged();
            }
        }
        private global::System.String _EventType;
        partial void OnEventTypeChanging(global::System.String value);
        partial void OnEventTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EventData
        {
            get
            {
                return _EventData;
            }
            set
            {
                OnEventDataChanging(value);
                ReportPropertyChanging("EventData");
                _EventData = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EventData");
                OnEventDataChanged();
            }
        }
        private global::System.String _EventData;
        partial void OnEventDataChanging(global::System.String value);
        partial void OnEventDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TaskName
        {
            get
            {
                return _TaskName;
            }
            set
            {
                OnTaskNameChanging(value);
                ReportPropertyChanging("TaskName");
                _TaskName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TaskName");
                OnTaskNameChanged();
            }
        }
        private global::System.String _TaskName;
        partial void OnTaskNameChanging(global::System.String value);
        partial void OnTaskNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventSummary
        {
            get
            {
                return _EventSummary;
            }
            set
            {
                OnEventSummaryChanging(value);
                ReportPropertyChanging("EventSummary");
                _EventSummary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventSummary");
                OnEventSummaryChanged();
            }
        }
        private global::System.String _EventSummary;
        partial void OnEventSummaryChanging(global::System.String value);
        partial void OnEventSummaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubjectID
        {
            get
            {
                return _SubjectID;
            }
            set
            {
                OnSubjectIDChanging(value);
                ReportPropertyChanging("SubjectID");
                _SubjectID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubjectID");
                OnSubjectIDChanged();
            }
        }
        private global::System.String _SubjectID;
        partial void OnSubjectIDChanging(global::System.String value);
        partial void OnSubjectIDChanged();

        #endregion

    
    }

    #endregion

    
}
