//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ATMStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ATMStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATM.ATMStrings", typeof(ATMStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT INFORMATION.
        /// </summary>
        internal static string AcctInformation {
            get {
                return ResourceManager.GetString("AcctInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available: $.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your task is to check the balance in your checking account.
        /// </summary>
        internal static string CheckBalanceReminder {
            get {
                return ResourceManager.GetString("CheckBalanceReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Account: $.
        /// </summary>
        internal static string CheckingAcct {
            get {
                return ResourceManager.GetString("CheckingAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking: *.
        /// </summary>
        internal static string CheckingAsterisk {
            get {
                return ResourceManager.GetString("CheckingAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking -&gt; Savings.
        /// </summary>
        internal static string CheckingToSavings {
            get {
                return ResourceManager.GetString("CheckingToSavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select OK to return to the language select screen. Select NO to stay where you are..
        /// </summary>
        internal static string ConfirmCancelSubtaskMessage {
            get {
                return ResourceManager.GetString("ConfirmCancelSubtaskMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPOSIT.
        /// </summary>
        internal static string DepositButton {
            get {
                return ResourceManager.GetString("DepositButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit this sub-task?.
        /// </summary>
        internal static string EndSubtaskEarlyMessage {
            get {
                return ResourceManager.GetString("EndSubtaskEarlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! Press Exit to close the ATM task.
        /// </summary>
        internal static string ExitAtmTaskMessage {
            get {
                return ResourceManager.GetString("ExitAtmTaskMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Task.
        /// </summary>
        internal static string ExitTaskButton {
            get {
                return ResourceManager.GetString("ExitTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much cash would you like?.
        /// </summary>
        internal static string HowMuchCashToWithdraw {
            get {
                return ResourceManager.GetString("HowMuchCashToWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your input is not valid. 
        ///			Please re-type PIN number..
        /// </summary>
        internal static string InvalidPIN {
            get {
                return ResourceManager.GetString("InvalidPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in your checking account.
        /// </summary>
        internal static string InYourCheckingAcct {
            get {
                return ResourceManager.GetString("InYourCheckingAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  in your checking account\nIn your checking account, $.
        /// </summary>
        internal static string InYourCheckingAcctTwice {
            get {
                return ResourceManager.GetString("InYourCheckingAcctTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  in your savings account.
        /// </summary>
        internal static string InYourSavingsAcct {
            get {
                return ResourceManager.GetString("InYourSavingsAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in your saving account\nIn your saving account, $.
        /// </summary>
        internal static string InYourSavingsAcctTwice {
            get {
                return ResourceManager.GetString("InYourSavingsAcctTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is available.
        /// </summary>
        internal static string IsAvailable {
            get {
                return ResourceManager.GetString("IsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first select the language before you can continue..
        /// </summary>
        internal static string MustSelectLanguage {
            get {
                return ResourceManager.GetString("MustSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! Press Continue to proceed to the next task.
        /// </summary>
        internal static string NextTaskPrompt {
            get {
                return ResourceManager.GetString("NextTaskPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, your checking account has $.
        /// </summary>
        internal static string NowCheckingAcctHas {
            get {
                return ResourceManager.GetString("NowCheckingAcctHas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        internal static string NumPadClear {
            get {
                return ResourceManager.GetString("NumPadClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER.
        /// </summary>
        internal static string NumPadEnter {
            get {
                return ResourceManager.GetString("NumPadEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I only have $10 and $20 bills..
        /// </summary>
        internal static string OnlyHave10and20 {
            get {
                return ResourceManager.GetString("OnlyHave10and20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attempt(s) remaining..
        /// </summary>
        internal static string PinTriesRemaining {
            get {
                return ResourceManager.GetString("PinTriesRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the amount required by subtask!($100).
        /// </summary>
        internal static string PleaseEnterAmtRequired100 {
            get {
                return ResourceManager.GetString("PleaseEnterAmtRequired100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the amount required by subtask!($50).
        /// </summary>
        internal static string PleaseEnterAmtRequired50 {
            get {
                return ResourceManager.GetString("PleaseEnterAmtRequired50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell me your Personal Identification Number
        ///using the keypad.
        ///Then press ENTER..
        /// </summary>
        internal static string PleaseEnterPIN {
            get {
                return ResourceManager.GetString("PleaseEnterPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do?
        ///
        ///Please make a selection below..
        /// </summary>
        internal static string PleaseMakeSelection {
            get {
                return ResourceManager.GetString("PleaseMakeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please retype the amount. I only support $10 and $20 bills..
        /// </summary>
        internal static string PleaseRetypeAmount10and20 {
            get {
                return ResourceManager.GetString("PleaseRetypeAmount10and20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please retype the amount. Your checking account has.
        /// </summary>
        internal static string PleaseRetypeAmtChecking {
            get {
                return ResourceManager.GetString("PleaseRetypeAmtChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please retype the amount. Your savings account has.
        /// </summary>
        internal static string PleaseRetypeAmtSavings {
            get {
                return ResourceManager.GetString("PleaseRetypeAmtSavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please retype the amount you want to transfer..
        /// </summary>
        internal static string PleaseRetypeTransferAmt {
            get {
                return ResourceManager.GetString("PleaseRetypeTransferAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a language.
        /// </summary>
        internal static string PleaseSelectLanguage {
            get {
                return ResourceManager.GetString("PleaseSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take the bills..
        /// </summary>
        internal static string PleaseTakeBills {
            get {
                return ResourceManager.GetString("PleaseTakeBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in the amount of cash you want to withdraw.
        /// </summary>
        internal static string PleaseTypeInCashAmt {
            get {
                return ResourceManager.GetString("PleaseTypeInCashAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in the amount you want to transfer..
        /// </summary>
        internal static string PleaseTypeTransferAmt {
            get {
                return ResourceManager.GetString("PleaseTypeTransferAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFERENCE.
        /// </summary>
        internal static string PreferenceButton {
            get {
                return ResourceManager.GetString("PreferenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need more time to complete this task?.
        /// </summary>
        internal static string PromptForMoreTime {
            get {
                return ResourceManager.GetString("PromptForMoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings Account: $.
        /// </summary>
        internal static string SavingsAcct {
            get {
                return ResourceManager.GetString("SavingsAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings: *.
        /// </summary>
        internal static string SavingsAsterisk {
            get {
                return ResourceManager.GetString("SavingsAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings -&gt; Checking.
        /// </summary>
        internal static string SavingsToChecking {
            get {
                return ResourceManager.GetString("SavingsToChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See account details.
        /// </summary>
        internal static string SeeAcctDetails {
            get {
                return ResourceManager.GetString("SeeAcctDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See summary of accounts.
        /// </summary>
        internal static string SeeSummaryAccts {
            get {
                return ResourceManager.GetString("SeeSummaryAccts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take back your checks..
        /// </summary>
        internal static string TakeBackYourChecks {
            get {
                return ResourceManager.GetString("TakeBackYourChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the ATM below to check the balance in your checking account.Your Account PIN is 1234..
        /// </summary>
        internal static string Task1_Instructions {
            get {
                return ResourceManager.GetString("Task1_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the ATM below to transfer 50 dollars from your savings account to your checking account. Your Account PIN is 1234..
        /// </summary>
        internal static string Task2_Instructions {
            get {
                return ResourceManager.GetString("Task2_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the ATM below to withdraw 100 dollars from your checking account. Your Account PIN is 1234..
        /// </summary>
        internal static string Task3_Instructions {
            get {
                return ResourceManager.GetString("Task3_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The available amount in your checking account is.
        /// </summary>
        internal static string TheAvailableAmtInCheckingIs {
            get {
                return ResourceManager.GetString("TheAvailableAmtInCheckingIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The available amount in your savings account is.
        /// </summary>
        internal static string TheAvailableAmtInSavingsIs {
            get {
                return ResourceManager.GetString("TheAvailableAmtInSavingsIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction completed successfully..
        /// </summary>
        internal static string TransactionDoneSuccessfully {
            get {
                return ResourceManager.GetString("TransactionDoneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your task is to transfer 50 dollars from your savings account to  your checking account .
        /// </summary>
        internal static string Transfer50DollarsReminder {
            get {
                return ResourceManager.GetString("Transfer50DollarsReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer between my accounts.
        /// </summary>
        internal static string TransferBetweenMyAccts {
            get {
                return ResourceManager.GetString("TransferBetweenMyAccts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSFER OR PAYMENT.
        /// </summary>
        internal static string TransferOrPayment {
            get {
                return ResourceManager.GetString("TransferOrPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to other U.S. accounts.
        /// </summary>
        internal static string TransferToOtherAcct {
            get {
                return ResourceManager.GetString("TransferToOtherAcct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do?.
        /// </summary>
        internal static string WhatWouldYouLikeToDo {
            get {
                return ResourceManager.GetString("WhatWouldYouLikeToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where would you like to transfer from?.
        /// </summary>
        internal static string WhereToTransferFrom {
            get {
                return ResourceManager.GetString("WhereToTransferFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where shall I get the money from?.
        /// </summary>
        internal static string WhereToWithdrawMoney {
            get {
                return ResourceManager.GetString("WhereToWithdrawMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your task is to withdraw 100 dollars from your checking account.
        /// </summary>
        internal static string WithdrawCashReminder {
            get {
                return ResourceManager.GetString("WithdrawCashReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have deposited $.
        /// </summary>
        internal static string YouHaveDeposited {
            get {
                return ResourceManager.GetString("YouHaveDeposited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your checking account ID: .
        /// </summary>
        internal static string YourCheckingAcctID {
            get {
                return ResourceManager.GetString("YourCheckingAcctID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your saving account has $.
        /// </summary>
        internal static string YourSavingsAcctHas {
            get {
                return ResourceManager.GetString("YourSavingsAcctHas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your saving account ID: .
        /// </summary>
        internal static string YourSavingsAcctID {
            get {
                return ResourceManager.GetString("YourSavingsAcctID", resourceCulture);
            }
        }
    }
}
