//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrescriptionRefill.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrescriptionRefill.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Ampliex {
            get {
                object obj = ResourceManager.GetObject("Ampliex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ampliex_ES {
            get {
                object obj = ResourceManager.GetObject("Ampliex_ES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap key1 {
            get {
                object obj = ResourceManager.GetObject("key1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap key2 {
            get {
                object obj = ResourceManager.GetObject("key2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Megalith {
            get {
                object obj = ResourceManager.GetObject("Megalith", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Megalith_ES {
            get {
                object obj = ResourceManager.GetObject("Megalith_ES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone {
            get {
                object obj = ResourceManager.GetObject("phone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone1 {
            get {
                object obj = ResourceManager.GetObject("phone1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] PRT_EN_err01 {
            get {
                object obj = ResourceManager.GetObject("PRT_EN_err01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_EN_err011 {
            get {
                object obj = ResourceManager.GetObject("PRT_EN_err011", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_EN_err012 {
            get {
                object obj = ResourceManager.GetObject("PRT_EN_err012", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_EN_err013 {
            get {
                object obj = ResourceManager.GetObject("PRT_EN_err013", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err02 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err02", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err021 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err021", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err022 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err022", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err023 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err023", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err03 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err03", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err031 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err031", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err032 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err032", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err033 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err033", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err04 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err04", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err041 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err041", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err042 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err042", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err043 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err043", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err05 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err05", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err051 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err051", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err052 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err052", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en_err053 {
            get {
                object obj = ResourceManager.GetObject("PRT_en_err053", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en01 {
            get {
                object obj = ResourceManager.GetObject("PRT_en01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Prt_en01_2 {
            get {
                object obj = ResourceManager.GetObject("Prt_en01_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en011 {
            get {
                object obj = ResourceManager.GetObject("PRT_en011", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en012 {
            get {
                object obj = ResourceManager.GetObject("PRT_en012", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en013 {
            get {
                object obj = ResourceManager.GetObject("PRT_en013", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en02 {
            get {
                object obj = ResourceManager.GetObject("PRT_en02", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en021 {
            get {
                object obj = ResourceManager.GetObject("PRT_en021", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en022 {
            get {
                object obj = ResourceManager.GetObject("PRT_en022", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en023 {
            get {
                object obj = ResourceManager.GetObject("PRT_en023", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en03 {
            get {
                object obj = ResourceManager.GetObject("PRT_en03", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en031 {
            get {
                object obj = ResourceManager.GetObject("PRT_en031", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en032 {
            get {
                object obj = ResourceManager.GetObject("PRT_en032", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en033 {
            get {
                object obj = ResourceManager.GetObject("PRT_en033", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en04 {
            get {
                object obj = ResourceManager.GetObject("PRT_en04", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en041 {
            get {
                object obj = ResourceManager.GetObject("PRT_en041", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en042 {
            get {
                object obj = ResourceManager.GetObject("PRT_en042", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en043 {
            get {
                object obj = ResourceManager.GetObject("PRT_en043", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en05 {
            get {
                object obj = ResourceManager.GetObject("PRT_en05", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en051 {
            get {
                object obj = ResourceManager.GetObject("PRT_en051", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en052 {
            get {
                object obj = ResourceManager.GetObject("PRT_en052", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en053 {
            get {
                object obj = ResourceManager.GetObject("PRT_en053", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en06 {
            get {
                object obj = ResourceManager.GetObject("PRT_en06", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en061 {
            get {
                object obj = ResourceManager.GetObject("PRT_en061", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en062 {
            get {
                object obj = ResourceManager.GetObject("PRT_en062", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en063 {
            get {
                object obj = ResourceManager.GetObject("PRT_en063", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en07a {
            get {
                object obj = ResourceManager.GetObject("PRT_en07a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_en07a1 {
            get {
                return ResourceManager.GetStream("PRT_en07a1", resourceCulture);
            }
        }
        
        internal static byte[] PRT_en07a2 {
            get {
                object obj = ResourceManager.GetObject("PRT_en07a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_en07a3 {
            get {
                return ResourceManager.GetStream("PRT_en07a3", resourceCulture);
            }
        }
        
        internal static byte[] PRT_en07a4 {
            get {
                object obj = ResourceManager.GetObject("PRT_en07a4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_en07a5 {
            get {
                return ResourceManager.GetStream("PRT_en07a5", resourceCulture);
            }
        }
        
        internal static byte[] PRT_en07a6 {
            get {
                object obj = ResourceManager.GetObject("PRT_en07a6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_en07a7 {
            get {
                return ResourceManager.GetStream("PRT_en07a7", resourceCulture);
            }
        }
        
        internal static byte[] PRT_en07b {
            get {
                object obj = ResourceManager.GetObject("PRT_en07b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_en07b1 {
            get {
                return ResourceManager.GetStream("PRT_en07b1", resourceCulture);
            }
        }
        
        internal static byte[] PRT_en07b2 {
            get {
                object obj = ResourceManager.GetObject("PRT_en07b2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_en07b3 {
            get {
                return ResourceManager.GetStream("PRT_en07b3", resourceCulture);
            }
        }
        
        internal static byte[] PRT_en07b4 {
            get {
                object obj = ResourceManager.GetObject("PRT_en07b4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_en07b5 {
            get {
                return ResourceManager.GetStream("PRT_en07b5", resourceCulture);
            }
        }
        
        internal static byte[] PRT_en07b6 {
            get {
                object obj = ResourceManager.GetObject("PRT_en07b6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_en07b7 {
            get {
                return ResourceManager.GetStream("PRT_en07b7", resourceCulture);
            }
        }
        
        internal static byte[] PRT_en08 {
            get {
                object obj = ResourceManager.GetObject("PRT_en08", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en081 {
            get {
                object obj = ResourceManager.GetObject("PRT_en081", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en082 {
            get {
                object obj = ResourceManager.GetObject("PRT_en082", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en083 {
            get {
                object obj = ResourceManager.GetObject("PRT_en083", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_en09 {
            get {
                object obj = ResourceManager.GetObject("PRT_en09", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_en091 {
            get {
                return ResourceManager.GetStream("PRT_en091", resourceCulture);
            }
        }
        
        internal static byte[] PRT_en092 {
            get {
                object obj = ResourceManager.GetObject("PRT_en092", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_en093 {
            get {
                return ResourceManager.GetStream("PRT_en093", resourceCulture);
            }
        }
        
        internal static byte[] PRT_en094 {
            get {
                object obj = ResourceManager.GetObject("PRT_en094", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_en095 {
            get {
                return ResourceManager.GetStream("PRT_en095", resourceCulture);
            }
        }
        
        internal static byte[] PRT_en096 {
            get {
                object obj = ResourceManager.GetObject("PRT_en096", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_en097 {
            get {
                return ResourceManager.GetStream("PRT_en097", resourceCulture);
            }
        }
        
        internal static byte[] PRT_intro {
            get {
                object obj = ResourceManager.GetObject("PRT_intro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_intro1 {
            get {
                object obj = ResourceManager.GetObject("PRT_intro1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream prt_intro2 {
            get {
                return ResourceManager.GetStream("prt_intro2", resourceCulture);
            }
        }
        
        internal static byte[] PRT_intro3 {
            get {
                object obj = ResourceManager.GetObject("PRT_intro3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream prt_intro4 {
            get {
                return ResourceManager.GetStream("prt_intro4", resourceCulture);
            }
        }
        
        internal static byte[] PRT_intro5 {
            get {
                object obj = ResourceManager.GetObject("PRT_intro5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream prt_intro6 {
            get {
                return ResourceManager.GetStream("prt_intro6", resourceCulture);
            }
        }
        
        internal static byte[] PRT_SP_err01 {
            get {
                object obj = ResourceManager.GetObject("PRT_SP_err01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_SP_err011 {
            get {
                object obj = ResourceManager.GetObject("PRT_SP_err011", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_SP_err012 {
            get {
                object obj = ResourceManager.GetObject("PRT_SP_err012", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_SP_err013 {
            get {
                object obj = ResourceManager.GetObject("PRT_SP_err013", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err02 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err02", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err021 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err021", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err022 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err022", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err023 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err023", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err03 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err03", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err031 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err031", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err032 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err032", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err033 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err033", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err04 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err04", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err041 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err041", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err042 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err042", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err043 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err043", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err05 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err05", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err051 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err051", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err052 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err052", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp_err053 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp_err053", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp02 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp02", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp021 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp021", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp022 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp022", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp023 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp023", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp03 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp03", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp031 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp031", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp032 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp032", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp033 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp033", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp04 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp04", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp041 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp041", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp042 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp042", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp043 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp043", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp05 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp05", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp051 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp051", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp052 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp052", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp053 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp053", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp06 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp06", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp061 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp061", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp062 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp062", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp063 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp063", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp07a {
            get {
                object obj = ResourceManager.GetObject("PRT_sp07a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_sp07a1 {
            get {
                return ResourceManager.GetStream("PRT_sp07a1", resourceCulture);
            }
        }
        
        internal static byte[] PRT_sp07a2 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp07a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_sp07a3 {
            get {
                return ResourceManager.GetStream("PRT_sp07a3", resourceCulture);
            }
        }
        
        internal static byte[] PRT_sp07a4 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp07a4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_sp07a5 {
            get {
                return ResourceManager.GetStream("PRT_sp07a5", resourceCulture);
            }
        }
        
        internal static byte[] PRT_sp07a6 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp07a6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_sp07a7 {
            get {
                return ResourceManager.GetStream("PRT_sp07a7", resourceCulture);
            }
        }
        
        internal static byte[] PRT_sp07b {
            get {
                object obj = ResourceManager.GetObject("PRT_sp07b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_sp07b1 {
            get {
                return ResourceManager.GetStream("PRT_sp07b1", resourceCulture);
            }
        }
        
        internal static byte[] PRT_sp07b2 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp07b2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_sp07b3 {
            get {
                return ResourceManager.GetStream("PRT_sp07b3", resourceCulture);
            }
        }
        
        internal static byte[] PRT_sp07b4 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp07b4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_sp07b5 {
            get {
                return ResourceManager.GetStream("PRT_sp07b5", resourceCulture);
            }
        }
        
        internal static byte[] PRT_sp07b6 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp07b6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_sp07b7 {
            get {
                return ResourceManager.GetStream("PRT_sp07b7", resourceCulture);
            }
        }
        
        internal static byte[] PRT_sp08 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp08", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp081 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp081", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp082 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp082", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp083 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp083", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PRT_sp09 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp09", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_sp091 {
            get {
                return ResourceManager.GetStream("PRT_sp091", resourceCulture);
            }
        }
        
        internal static byte[] PRT_sp092 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp092", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_sp093 {
            get {
                return ResourceManager.GetStream("PRT_sp093", resourceCulture);
            }
        }
        
        internal static byte[] PRT_sp094 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp094", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_sp095 {
            get {
                return ResourceManager.GetStream("PRT_sp095", resourceCulture);
            }
        }
        
        internal static byte[] PRT_sp096 {
            get {
                object obj = ResourceManager.GetObject("PRT_sp096", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PRT_sp097 {
            get {
                return ResourceManager.GetStream("PRT_sp097", resourceCulture);
            }
        }
    }
}
