//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactionTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InstructionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstructionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReactionTest.InstructionStrings", typeof(InstructionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not press the key until the target appears.
        /// </summary>
        internal static string EarlyPressWarning {
            get {
                return ResourceManager.GetString("EarlyPressWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Reaction Time Task*
        ///
        ///In this task you will be responding to a green square
        ///
        ///Sometimes you will be asked to press one key when the green square appears
        ///
        ///Other times you will press one of two keys depending on where the square appears
        ///
        ///Please try to be as fast as possible
        ///
        ///Detailed instructions will follow
        ///
        ///(press the space bar to continue).
        /// </summary>
        internal static string InstructionsPart1 {
            get {
                return ResourceManager.GetString("InstructionsPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target you will be responding to will look like the green square below.
        ///(press the space bar to continue).
        /// </summary>
        internal static string InstructionsPart2 {
            get {
                return ResourceManager.GetString("InstructionsPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Task1: Simple Reaction Time Task
        ///
        ///
        ///*As soon as the square appears, press the B key as quickly as possible
        ///
        ///
        ///(Make sure your finger is on the B key now. Press the space bar to begin).
        /// </summary>
        internal static string InstructionsPart3 {
            get {
                return ResourceManager.GetString("InstructionsPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Task 2: Complex Reaction Time*
        ///
        ///
        ///This time your task will be different
        ///
        ///
        ///The green square will appear on either the left or right side of the screen
        ///
        ///If the square appears on the left, press the Z key (on the left)
        ///
        ///If the square appears on the right, press the / key (on the right)
        ///
        ///As soon as the square appears, make your response as quickly as possible
        ///
        ///(Make sure you have one finger on the Z key, and one on the / key before you begin. Press the space bar now to begin).
        /// </summary>
        internal static string InstructionsPart4 {
            get {
                return ResourceManager.GetString("InstructionsPart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Task1 Again: Simple Reaction Time Task*
        ///
        ///
        ///We will now do the Simple Reaction Time task again
        ///
        ///You will see a green square appear in the middle of the screen
        ///
        /// As soon as the square appears, press the  B key as quickly as possible
        ///
        ///(Make sure your finger is on the B key now. Press the space bar to begin).
        /// </summary>
        internal static string InstructionsPart5 {
            get {
                return ResourceManager.GetString("InstructionsPart5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for completing this task.
        /// </summary>
        internal static string ThankYouMessage {
            get {
                return ResourceManager.GetString("ThankYouMessage", resourceCulture);
            }
        }
    }
}
