//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ReactionTest
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SimpleReaction> SimpleReactions
        {
            get
            {
                if ((_SimpleReactions == null))
                {
                    _SimpleReactions = base.CreateObjectSet<SimpleReaction>("SimpleReactions");
                }
                return _SimpleReactions;
            }
        }
        private ObjectSet<SimpleReaction> _SimpleReactions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ComplexReaction> ComplexReactions
        {
            get
            {
                if ((_ComplexReactions == null))
                {
                    _ComplexReactions = base.CreateObjectSet<ComplexReaction>("ComplexReactions");
                }
                return _ComplexReactions;
            }
        }
        private ObjectSet<ComplexReaction> _ComplexReactions;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SimpleReactions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSimpleReactions(SimpleReaction simpleReaction)
        {
            base.AddObject("SimpleReactions", simpleReaction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ComplexReactions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComplexReactions(ComplexReaction complexReaction)
        {
            base.AddObject("ComplexReactions", complexReaction);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="ComplexReaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ComplexReaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ComplexReaction object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="color">Initial value of the Color property.</param>
        /// <param name="delay">Initial value of the Delay property.</param>
        /// <param name="location">Initial value of the Location property.</param>
        /// <param name="height">Initial value of the Height property.</param>
        /// <param name="width">Initial value of the Width property.</param>
        /// <param name="touch">Initial value of the Touch property.</param>
        /// <param name="key">Initial value of the Key property.</param>
        /// <param name="life">Initial value of the Life property.</param>
        public static ComplexReaction CreateComplexReaction(global::System.Int32 id, global::System.String color, global::System.Int32 delay, global::System.String location, global::System.Int32 height, global::System.Int32 width, global::System.String touch, global::System.String key, global::System.Int32 life)
        {
            ComplexReaction complexReaction = new ComplexReaction();
            complexReaction.Id = id;
            complexReaction.Color = color;
            complexReaction.Delay = delay;
            complexReaction.Location = location;
            complexReaction.Height = height;
            complexReaction.Width = width;
            complexReaction.Touch = touch;
            complexReaction.Key = key;
            complexReaction.Life = life;
            return complexReaction;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Delay
        {
            get
            {
                return _Delay;
            }
            set
            {
                OnDelayChanging(value);
                ReportPropertyChanging("Delay");
                _Delay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delay");
                OnDelayChanged();
            }
        }
        private global::System.Int32 _Delay;
        partial void OnDelayChanging(global::System.Int32 value);
        partial void OnDelayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private global::System.Int32 _Height;
        partial void OnHeightChanging(global::System.Int32 value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private global::System.Int32 _Width;
        partial void OnWidthChanging(global::System.Int32 value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Touch
        {
            get
            {
                return _Touch;
            }
            set
            {
                OnTouchChanging(value);
                ReportPropertyChanging("Touch");
                _Touch = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Touch");
                OnTouchChanged();
            }
        }
        private global::System.String _Touch;
        partial void OnTouchChanging(global::System.String value);
        partial void OnTouchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Key
        {
            get
            {
                return _Key;
            }
            set
            {
                OnKeyChanging(value);
                ReportPropertyChanging("Key");
                _Key = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Key");
                OnKeyChanged();
            }
        }
        private global::System.String _Key;
        partial void OnKeyChanging(global::System.String value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Life
        {
            get
            {
                return _Life;
            }
            set
            {
                OnLifeChanging(value);
                ReportPropertyChanging("Life");
                _Life = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Life");
                OnLifeChanged();
            }
        }
        private global::System.Int32 _Life;
        partial void OnLifeChanging(global::System.Int32 value);
        partial void OnLifeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="SimpleReaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SimpleReaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SimpleReaction object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="color">Initial value of the Color property.</param>
        /// <param name="delay">Initial value of the Delay property.</param>
        /// <param name="location">Initial value of the Location property.</param>
        /// <param name="height">Initial value of the Height property.</param>
        /// <param name="width">Initial value of the Width property.</param>
        /// <param name="touch">Initial value of the Touch property.</param>
        /// <param name="key">Initial value of the Key property.</param>
        /// <param name="life">Initial value of the Life property.</param>
        public static SimpleReaction CreateSimpleReaction(global::System.Int32 id, global::System.String color, global::System.Int32 delay, global::System.String location, global::System.Int32 height, global::System.Int32 width, global::System.String touch, global::System.String key, global::System.Int32 life)
        {
            SimpleReaction simpleReaction = new SimpleReaction();
            simpleReaction.Id = id;
            simpleReaction.Color = color;
            simpleReaction.Delay = delay;
            simpleReaction.Location = location;
            simpleReaction.Height = height;
            simpleReaction.Width = width;
            simpleReaction.Touch = touch;
            simpleReaction.Key = key;
            simpleReaction.Life = life;
            return simpleReaction;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Delay
        {
            get
            {
                return _Delay;
            }
            set
            {
                OnDelayChanging(value);
                ReportPropertyChanging("Delay");
                _Delay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delay");
                OnDelayChanged();
            }
        }
        private global::System.Int32 _Delay;
        partial void OnDelayChanging(global::System.Int32 value);
        partial void OnDelayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private global::System.Int32 _Height;
        partial void OnHeightChanging(global::System.Int32 value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private global::System.Int32 _Width;
        partial void OnWidthChanging(global::System.Int32 value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Touch
        {
            get
            {
                return _Touch;
            }
            set
            {
                OnTouchChanging(value);
                ReportPropertyChanging("Touch");
                _Touch = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Touch");
                OnTouchChanged();
            }
        }
        private global::System.String _Touch;
        partial void OnTouchChanging(global::System.String value);
        partial void OnTouchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Key
        {
            get
            {
                return _Key;
            }
            set
            {
                OnKeyChanging(value);
                ReportPropertyChanging("Key");
                _Key = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Key");
                OnKeyChanged();
            }
        }
        private global::System.String _Key;
        partial void OnKeyChanging(global::System.String value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Life
        {
            get
            {
                return _Life;
            }
            set
            {
                OnLifeChanging(value);
                ReportPropertyChanging("Life");
                _Life = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Life");
                OnLifeChanged();
            }
        }
        private global::System.Int32 _Life;
        partial void OnLifeChanging(global::System.Int32 value);
        partial void OnLifeChanged();

        #endregion

    
    }

    #endregion

    
}
